FROM apache/airflow:2.9.3-python3.11

ARG SPACY_MODEL_URL=https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl
ARG SCISPACY_MODEL_URL=https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_md-0.5.4.tar.gz
ARG AIRFLOW_CONSTRAINTS_URL=https://raw.githubusercontent.com/apache/airflow/constraints-2.9.3/constraints-3.11.txt

ENV NLTK_DATA=/home/airflow/nltk_data

COPY --chown=airflow:root requirements-airflow.txt /tmp/requirements-airflow.txt

RUN pip install --no-cache-dir \
        --constraint "${AIRFLOW_CONSTRAINTS_URL}" \
        --requirement /tmp/requirements-airflow.txt \
    && python -m nltk.downloader -d "${NLTK_DATA}" stopwords \
    && pip install --no-cache-dir \
        --constraint "${AIRFLOW_CONSTRAINTS_URL}" \
        "${SPACY_MODEL_URL}" "${SCISPACY_MODEL_URL}" \
    && pip check \
    && rm -f /tmp/requirements-airflow.txt \
    && rm -rf /home/airflow/.cache
